import Head from "next/head";
import Layout from "../components/Layout";
import Hero from "../components/Hero";
import Service from "../components/Service";
import Collection from "../components/Collection";

export default function Home() {
  return (
    <Layout>
      <div>
        <Head>
          <title>Hima Florist</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/Logo.png" />
        </Head>
        {/* body */}
        <main>
           <Hero />
          <Service />
          <Collection /> 
        </main>
      </div>
    </Layout>
  );
}
